server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceIrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    witTimeInMsWhenSyncEmpty: 0
