# sidecar is designed to be executed in the same host as main microservices ( localhost), but this is different when
# using docker containers.
# 1. preferIpAddress should be set to "false" when using separate container for main microservice. SO that the hostname is
#used instead of the ipaddress


server:
  port: 5678

spring:
  application:
    name: product-catalog
server.servlet-path: /
management.context-path: /admin

#
sidecar:
  hostname: ${SIDECAR_HOSTNAME:localhost}
  port: ${SIDECAR_PORT:8000}
  health-uri: ${SIDECAR_HEALTH_URI:http://localhost:8000/health}


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    appname: ${spring.application.name}
    hostname: ${sidecar.hostname}
    healthCheckUrlPath: ${sidecar.health-uri}
    preferIpAddress: false
    metadataMap:
      instanceId: ${spring.application.name}:${sidecar.port}
